### PR TITLE
Changed README format to Markdown

### PR DESCRIPTION
**Pull request by nicoddemus**
This fixes icefox/git-hooks#19.

### CODE REVIEW

**Comment by zbeekman** [comment]
:+1:

**Comment by nicoddemus** [comment]
Is there still interest in this? If so I can rebase/solve the conflicts.

**Comment by icefox** [comment]
Yeah, just been busy, if I have you push access would you be interested in going through all of the pull requests?

**Comment by nicoddemus** [comment]
Don't really have time for it, sorry 😞

**Comment by molovo** [comment]
This has already been fixed in 786e70a and #19 is closed, so this is no longer needed.

**Pull request closed without merging**
