### PR TITLE
Add a json validator, utilzing python's json.tool

### PR DESCRIPTION
**Pull request by apg**
I've been using this json pre-commit hook -- it's saved me on multiple occassions!

### CODE REVIEW

**Comment by Krettis** [comment]
Only check on the changed json files.

**Comment by jalcine** [comment]
@Krettis how does one obtain a list of changed files?
`git show HEAD --name-only` seems to work but there's difftext in there.

**Comment by Krettis** [comment]
@jalcine git diff --cached --name-only
This shows you what you are about to commit.

Maybe you only want to check certain files with certain statuses:
'git diff --cached --name-only`

**Comment by jalcine** [comment]
On Monday, May 11, 2015 04:07:48 AM krettis wrote:
> @jalcine git diff --cached --name-only
> This shows you what you are about to commit.

Gotcha! Might make that into an alias :)
-- 
Jacky Alcine, web developer on a sugar high
https://jacky.wtf
#BlackLivesMatter

**Comment by Krettis** [comment]
@jalcine Only alias when you already master the the full command ;)

**Comment by apg** [comment]
FWIW, I no longer use this repo, so if you choose to move forward, do as you will! :smile:

**Comment by molovo** [comment]
Abandoned, closing.

**Pull request closed without merging**
