### PR TITLE
Add support for project custom hooks directory

### PR DESCRIPTION
**Pull request by mindaugasrukas**

### CODE REVIEW

**Comment by Krettis** [comment]
Wouldn't be subscription of different repositories a better idea?

**Comment by mindaugasrukas** [comment]
Yes, this is what we want to achieve. We have a code standard, hooks and etc. in different repos, and want to include them into project with composer or other dependency manager. So the option for custom hooks dir would be very useful.

**Comment by zbeekman** [comment]
@Krettis I don’t understand what you are suggesting…

**Comment by Krettis** [comment]
@zbeekman Instead of waiting for each pull request for contributions on this repo, you could use different repositories with their own set of git-hooks. So you got a list of repos you've subscribed to who provide with a nice list of hooks.
That way you can check which hook you'll use and which not.

**Comment by zbeekman** [comment]
I think the point of this PR is so that coding standards in the form of hooks can be added directly to the repository containing the code. Then if git-hooks is installed when the project is cloned, by default the hooks it contains are enabled… I think that’s what @mindaugasrukas is trying to accomplish, which, if I understand you correctly, is different than what you’re suggesting.

**Comment by Krettis** [comment]
@zbeekman That is why it was a suggestion. 
It could be a follow up

**Comment by jasonkarns** [comment]
Is this not covered by:
```
git config --global hooks.global $PWD/contrib/
```

**Comment by mindaugasrukas** [comment]
I don't need this PR anymore.

**Pull request closed without merging**
