### PR TITLE
Use "git-hooks" instead of "git hooks" in docs

### PR DESCRIPTION
**Pull request by emmetog**

### CODE REVIEW

**Comment by emmetog** [comment]
This caused a bit of confusion for me, I was never certain if this should be `git-hooks` or `git hooks`. By installing the executable as described in the README I understand the command should be `git-hooks`, am I wrong?

**Comment by molovo** [comment]
All of `git`'s subcommands are actually external executables, and follow the same structure as `git-hooks` beneath the hood. e.g. `git commit -> git-commit`, `git add -> git-add`. With that in mind, I'd be inclined to leave it as `git hooks`, as the pattern is well established.

Having said that, this PR doesn't prevent either usage from working, and so a user following the instructions won't see any difference either way. I'll leave this issue open for a little while, and let people vote on it (Just `+1`/`-1` the PR), and we'll go with the community consensus.

**Comment by emmetog** [comment]
@molovo I never realized that git did that with subcommands, thanks for the tip.

I've added a bit of an explanation about this to the README, hopefully it will help prevent some confusion for people who don't know the trick with the git subcommands.

If you want me to change all the examples from `git-hooks` to `git hooks` just let me know.

**Comment by molovo** [comment]
👍 @emmetog Works for me. Thanks for the PR

**Pull request merged**
